# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Checkout pheromone
        run: git submodule update --init
      - name: Build with Gradle
        run: HiveAR/gradlew.bat assembleDebug --stacktrace
      - name : Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: HiveAR/app/build/outputs/apk/debug/app-debug.apk